### Create an Item
POST http://localhost:8080/api/items
Content-Type: application/json

{
  "name": "keyboard",
  "quantity": 3,
  "price": 79.99
}

### Create an Item
POST http://localhost:8080/api/items
Content-Type: application/json

{
  "name": "Iphone",
  "quantity": 1,
  "price": 800.00
}

### Get Item by ID

GET localhost:8080/api/items/2

### Get Item by ID expecting error

GET localhost:8080/api/items/200

### Get All Items

GET http://localhost:8080/api/items

### Update item 1
PUT http://localhost:8080/api/items/1
Content-Type: application/json

{
  "name": "Updated Name",
  "quantity": 99,
  "price": 12.34
}

### Delete item by ID
DELETE http://localhost:8080/api/items/1

### Verify deletion
GET http://localhost:8080/api/items/1
